name: Issue Automation
on:
  issues:
    types: [opened]

permissions:
  contents: none
  issues: write

jobs:
  issue-auto:
    runs-on: ubuntu-latest
    steps:
      - name: label incoming issue
        env:
          GOCTL_REPO: ${{ github.repository }}
          GOCTL_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
          ISSUENUM: ${{ github.event.issue.number }}
          ISSUEAUTHOR: ${{ github.event.issue.user.login }}
        run: |
          if ! goctl api orgs/cli/public_members/$ISSUEAUTHOR --silent 2>/dev/null
          then
            goctl issue edit $ISSUENUM --add-label "needs-triage"
          fi